// src/ui/components/layout/modules/navbar.tsx
'use client';

import Link from 'next/link';

import { LanguageToggle } from '@/ui/components/language';

export function Navbar(): JSX.Element {
  return (
    <header className="fixed top-4 z-50 flex w-full items-center justify-center">
      <nav className="relative flex h-16 w-full max-w-3xl items-center rounded-md border border-border bg-background/10 px-4 backdrop-blur-md">
        {/* Logo */}
        <Link href="/">
          <h1 className="w-fit text-2xl font-semibold tracking-widest duration-150 hover:text-emerald-500">Hermel</h1>
        </Link>
        {/* Links */}
        <section className="flex basis-1/2 items-center justify-center"></section>
        {/* Options */}
        <section className="flex basis-1/2 items-center justify-end gap-4">
          <LanguageToggle />
          {/* <ThemeToggle /> */}
        </section>
      </nav>
    </header>
  );
}

// src/components/layout/Navbar.vue
<script lang="ts" setup>
import { RouterLink } from 'vue-router';

import { LanguageToggle } from '@/components/language';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { AtSign } from 'lucide-vue-next';
</script>

<template>
  <header :class="cn('fixed z-[999] sm:top-4', 'flex w-full items-center justify-center')">
    <nav
      :class="
        cn(
          'relative',
          'flex items-center justify-between gap-4',
          'h-16 max-w-3xl w-full',
          'px-4 border-b sm:border border-border border-dashed sm:rounded-md',
          'bg-gradient-to-br from-background/30 to-neutral-800/30 backdrop-blur-md'
        )
      "
    >
      <!-- Logo -->
      <section>
        <RouterLink to="/" class="font-geist text-3xl duration-300 hover:text-emerald-500 font-normal">
          <span>her</span>
          <span class="-ml-[4px]">mel</span>
        </RouterLink>
      </section>
      <!-- Options -->
      <section class="basis-1/5 sm:flex gap-4 justify-end hidden">
        <RouterLink to="/contact" :class="`${buttonVariants({ variant: 'outline', size: 'sm' })} bg-transparent gap-1`">
          <AtSign class="w-5 h-5" />
          {{ $t('navbar.contact') }}
        </RouterLink>
        <LanguageToggle />
      </section>
    </nav>
  </header>
</template>
