// src/ui/components/layout/modules/section.tsx
import { ComponentPropsWithoutRef, forwardRef } from 'react';

interface SectionProps extends ComponentPropsWithoutRef<'section'> {}

export const Section = forwardRef<HTMLElement, SectionProps>(function RenderSection(props, ref): JSX.Element {
  return (
    <section {...props} ref={ref} className="border-b border-dashed border-border">
      <section className="container relative flex flex-col gap-8 border-dashed border-border p-4 sm:border-x sm:p-16">
        {props.children}
      </section>
    </section>
  );
});

// src/components/layout/Section.vue
<script setup lang="ts">
import { cn } from '@/utils/cn';

defineProps({
  title: String,
  subtitle: String
});
</script>

<template>
  <section class="border-b border-dashed border-border">
    <section
      :class="
        cn(
          'container relative',
          'flex flex-col gap-6 sm:gap-8',
          'py-8 px-4 sm:p-16 border-dashed border-border sm:border-x'
        )
      "
    >
      <hgroup>
        <h2 class="text-2xl font-medium tracking-wider">{{ title }}</h2>
        <p class="text-muted-foreground">{{ subtitle }}</p>
      </hgroup>
      <slot></slot>
    </section>
  </section>
</template>
