// src/components/language/LanguageToggle.vue
<script lang="ts" setup>
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';

const countryName: { [key: string]: string } = {
  'pt-BR': 'Brazil',
  'en-US': 'United States'
};
</script>

<template>
  <DropdownMenu>
    <DropdownMenuTrigger as-child>
      <Button variant="outline" size="sm" class="gap-2 px-5">
        <img
          :src="`/languages/${$i18n.locale}.png`"
          :alt="`${countryName[$i18n.locale]}'s flag`"
          class="w-5 object-fit"
        />
        {{ $i18n.locale }}
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent>
      <DropdownMenuItem class="flex gap-2" @click="$i18n.locale = 'pt-BR'">
        <img src="/languages/pt-BR.png" alt="Brazil's flag" class="w-5 object-fit" /> BR
      </DropdownMenuItem>
      <DropdownMenuItem class="flex gap-2" @click="$i18n.locale = 'en-US'">
        <img src="/languages/en-US.png" alt="United States's flag" class="w-5 object-fit" /> EN
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

// src/ui/components/language/modules/language-toggle.tsx
'use client';

// #region Imports

import Image from 'next/image';

import { useLanguage } from '@/ui/components/language';
import { Button } from '@/ui/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/ui/components/ui/dropdown-menu';

// #endregion

/**
 * The available languages options.
 */
const LANGUAGES_OPTIONS: { [key: string]: { flag: string; name: string; alt: string } } = {
  'pt-BR': {
    flag: '/languages/pt-BR.png',
    name: 'BR',
    alt: 'Brasil',
  },
  'en-US': {
    flag: '/languages/en-US.png',
    name: 'EN',
    alt: 'United States',
  },
};

/**
 * Renders a language toggle component.
 *
 * @component
 * @returns {JSX.Element} The language toggle component.
 */
export function LanguageToggle(): JSX.Element {
  const { language, setLanguage } = useLanguage();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Image
            src={LANGUAGES_OPTIONS[language].flag}
            alt={`${LANGUAGES_OPTIONS[language].alt}'s flag`}
            width={24}
            height={24}
          />
          {language}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="z-[999] bg-background/60 backdrop-blur-md">
        <DropdownMenuItem className="flex gap-2" onClick={() => setLanguage('pt-BR')}>
          <>
            <Image src="/languages/pt-BR.png" alt="Brasil's flag" width={24} height={24} />
            BR
          </>
        </DropdownMenuItem>
        <DropdownMenuItem className="flex gap-2" onClick={() => setLanguage('en-US')}>
          <>
            <Image src="/languages/en-US.png" alt="United States's flag" width={24} height={24} />
            EN
          </>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
