// src/components/layout/Footer.vue
<script setup lang="ts">
import { LanguageToggle } from '@/components/language';
import { Button, buttonVariants } from '@/components/ui/button';
import { Github, Linkedin } from 'lucide-vue-next';
import { RouterLink } from 'vue-router';
</script>

<template>
  <footer class="w-full">
    <!-- Footer -->
    <section class="container flex items-center justify-between sm:p-16 p-4">
      <!-- Social Media Links -->
      <section class="flex gap-4">
        <a
          :class="`${buttonVariants({ variant: 'outline', size: 'icon' })} cursor-pointer`"
          href="https://github.com/h3rmel"
          target="_blank"
        >
          <Github /> </a
        ><a
          :class="`${buttonVariants({ variant: 'outline', size: 'icon' })} cursor-pointer`"
          href="https://linkedin.com/in/isaachermel"
          target="_blank"
        >
          <Linkedin />
        </a>
      </section>
      <LanguageToggle />
    </section>
    <!-- Copyright -->
    <section class="flex items-center justify-center border-t border-dashed py-2">
      Isaac "Hermel" Reginato &copy; {{ new Date().getFullYear() }}
    </section>
  </footer>
</template>

// src/ui/components/layout/modules/footer.tsx
'use client';

// #region Imports

import Link from 'next/link';

import { Github, Linkedin } from 'lucide-react';

import { LanguageToggle } from '@/ui/components/language';
import { Button } from '@/ui/components/ui/button';
import { Separator } from '@/ui/components/ui/separator';

// #endregion

/**
 * Renders a footer component.
 *
 * @component
 * @returns {JSX.Element} The footer component.
 */
export function Footer(): JSX.Element {
  return (
    <footer className="bg-dots w-full bg-fixed">
      <section className="container flex flex-col items-center justify-between gap-4 p-4 sm:flex-row sm:gap-0 sm:p-16">
        <section className="flex flex-col items-center gap-2 sm:flex-col sm:items-start sm:gap-4">
          <hgroup className="text-center sm:text-left">
            <h3 className="text-xl">Isaac "Hermel" Reginato.</h3>
            <p className="text-sm text-muted-foreground">&copy; 2024</p>
          </hgroup>
          <ul className="inline-flex items-center gap-2">
            <li>
              <Button variant="outline" size="icon" asChild>
                <Link href="https://github.com/h3rmel" target="_blank" aria-label="Github link">
                  <Github className="h-4 w-4" />
                </Link>
              </Button>
            </li>
            <li>
              <Button variant="outline" size="icon" asChild>
                <Link href="https://www.linkedin.com/in/isaachermel/" target="_blank" aria-label="Linkedin link">
                  <Linkedin className="h-4 w-4" />
                </Link>
              </Button>
            </li>
          </ul>
        </section>
        <Separator className="block sm:hidden" />
        <LanguageToggle />
      </section>
    </footer>
  );
}
