// src/components/layout/navbar/Navbar.vue
<script lang="ts" setup>
import { LanguageToggle } from '@/components/language';
import { cn } from '@/lib/utils';
import { NavbarLinks } from '../navbar-links';
import { Button } from '@/components/ui/button';
</script>

<template>
  <header :class="cn('fixed z-[999] sm:top-4', 'flex w-full items-center justify-center')">
    <nav
      :class="
        cn(
          'relative',
          'flex items-center justify-between gap-4',
          'h-16 max-w-3xl w-full',
          'px-4 border-b sm:border border-border sm:rounded-md',
          'bg-gradient-to-br from-background/30 to-neutral-800/30 backdrop-blur-md'
        )
      "
    >
      <!-- Logo -->
      <section class="basis-1/3">
        <Button variant="logo" class="p-0 duration-300">
          <span>her</span>
          <span class="-ml-1">mel</span>
        </Button>
      </section>
      <!-- Links -->
      <section class="basis-1/3 sm:flex justify-center hidden">
        <NavbarLinks />
      </section>
      <!-- Options -->
      <section class="basis-1/3 sm:flex justify-end hidden">
        <LanguageToggle />
      </section>
    </nav>
  </header>
</template>

// src/ui/components/layout/modules/navbar.tsx
'use client';

import Link from 'next/link';

import { LanguageToggle } from '@/ui/components/language';

export function Navbar(): JSX.Element {
  return (
    <header className="fixed top-4 z-50 flex w-full items-center justify-center">
      <nav className="relative flex h-16 w-full max-w-3xl items-center rounded-md border border-border bg-background/10 px-4 backdrop-blur-md">
        {/* Logo */}
        <Link href="/">
          <h1 className="w-fit text-2xl font-semibold tracking-widest duration-150 hover:text-emerald-500">Hermel</h1>
        </Link>
        {/* Links */}
        <section className="flex basis-1/2 items-center justify-center"></section>
        {/* Options */}
        <section className="flex basis-1/2 items-center justify-end gap-4">
          <LanguageToggle />
          {/* <ThemeToggle /> */}
        </section>
      </nav>
    </header>
  );
}
